# The name of this app. Must be unique within a project.
name: resume_slayer

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the Python documentation
# (https://docs.platform.sh/languages/python.html#supported-versions)
# to find the supported versions for the 'python' type.
type: 'python:3.11'

# The size of the persistent disk of the application (in MB).
disk: 2048

hooks:
    build: |
      set -eu

      pip install -r requirements.txt
web:
  commands: 
    start: "python -m uvicorn main:app --port $PORT"
  locations:
    '/':
      passthru: true
      request_buffering:
        enabled: false
